# Generated by Django 5.0.6 on 2024-07-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Davlat', 'verbose_name_plural': 'Davlatlar'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ManyToManyField(blank=True, to='tours.category'),
        ),
    ]
