# Generated by Django 5.0.6 on 2024-07-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0003_category_alter_country_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tour",
            old_name="category",
            new_name="categories",
        ),
    ]
