# Generated by Django 5.0.6 on 2024-07-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_rename_category_tour_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
