# Generated by Django 5.0.6 on 2024-07-13 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0005_category_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("has_breakfast", models.BooleanField(default=True)),
                ("has_lunch", models.BooleanField(default=False)),
                ("has_dinner", models.BooleanField(default=False)),
                ("breakfast", models.TextField(blank=True, null=True)),
                ("lunch", models.TextField(blank=True, null=True)),
                ("dinner", models.TextField(blank=True, null=True)),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tours.tour"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
