# Generated by Django 5.0.6 on 2024-07-13 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0006_food"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food",
                to="tours.tour",
            ),
        ),
    ]
