# Generated by Django 5.0.6 on 2024-07-13 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0007_alter_food_tour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="tour",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food",
                to="tours.tour",
            ),
        ),
    ]
