# Generated by Django 5.0.6 on 2024-07-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0008_alter_food_tour"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("stars", models.PositiveSmallIntegerField(default=1)),
                ("image", models.ImageField(upload_to="hotels/")),
                ("address", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HotelFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tour",
            name="hotels",
            field=models.ManyToManyField(blank=True, to="tours.hotel"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="facilities",
            field=models.ManyToManyField(blank=True, to="tours.hotelfacility"),
        ),
    ]
