# Generated by Django 5.0.6 on 2024-07-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0009_hotel_hotelfacility_tour_hotels_hotel_facilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="hit_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
