# Generated by Django 5.0.6 on 2024-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0010_tour_hit_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="hotel_class",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
