# Generated by Django 5.0.6 on 2024-07-16 16:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0012_hotel_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="price_list",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tour",
            name="programm",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tour",
            name="visa",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
