# Generated by Django 5.0.6 on 2024-07-18 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tours", "0014_tourreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("PAID", "Paid"),
                            ("TICKET_ISSUED", "Ticket Issued"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUND_REQUESTED", "Refund Requested"),
                            ("REFUNDED", "Refunded"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("tourist_count", models.PositiveSmallIntegerField(default=1)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tours.tour",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
