# Generated by Django 5.0.6 on 2024-07-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="tourist_count",
            new_name="adult_count",
        ),
        migrations.AddField(
            model_name="booking",
            name="kid_count",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="booking",
            name="pet_count",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
